### ISSUE TITLE
Hello!, I'm interested in collaborating with this project by offering a translation to Spanish, which is my native language.

### ISSUE THREAD

**Issue by LuigiBaute** [Azure/open-service-broker-azure#261]

**Comment by krancour** [comment]
Hi @LuigiBaute thanks for the offer. I think we're probably going to take you up on that, but give us a chance to have a quick internal conversation about this before you get going on it.

We're still trying to figure out how/where we're actually going to host docs and as part of that, we should discuss what our plan is going to be for long-term maintenance of community-driven doc translations. Internally, we don't have the expertise or the bandwidth to keep those translations up to date on an ongoing basis, so we'll need to establish a process for keeping them up to date with the help of volunteers such as yourself. We may also have to note explicitly that the translations may, at time, not be 100% up to date.

I'll get back to you within the next fews days!

**Comment by LuigiBaute** [comment]
Ok, Ill be looking forward to make my contribution!

**Comment by LuigiBaute** [comment]
Hello there my friend, have you tought about my contribution proposal? let me know if I should get started!

**Comment by krancour** [comment]
Hi @LuigiBaute, we discussed this morning and while I feel there are some unanswered questions about how we'll manage this long-term (how, for instance, do non-Spanish speaking maintainers review Spanish doc PRs?) but overall, we _do_ want this. So I would say go ahead and get started and we'll figure out whatever course corrections are needed as we go.

Thanks for volunteering to do this. I'm excited for this!

**Comment by LuigiBaute** [comment]
I'll start on the readme file and `I'd like to know` if I could do any other document and Ima tell you why: I work for utopian as a translator my contributions need to have over a thousand words the README has 1.9k which means that if I do any other file they'll validate me 2 contributions instead of one. let me know `THANKS` Cheers! :+1:  @krancour

**Comment by krancour** [comment]
@LuigiBaute I don't think we realized that you were getting paid just to do translations. That's a neat model. I don't think any of us maintainers are philosophically opposed to people being paid to make contributions to open source (I mean... we are, after all).

What I have to ask though is what your level of comfort is with the technologies you'd be documenting. Do you have experience with Kubernetes, minikube, Cloud Foundry, service brokers, etc.? imo, a strong command of both English and Spanish may not be sufficient to produce accurate translations here if you don't also posses an understanding of the technology.

lmk

**Comment by LuigiBaute** [comment]
@krancour I do not have such experience. BUT I do have experience translating and if I got an issue with some word I'll let you know if thats allright? When I read the Readme what I saw was basically indications on what it is, how to install, quick start etc... If you think about it you guys have the information I'm just making it understandable to Spanish talking poblation.

**Comment by krancour** [comment]
@LuigiBaute, the project maintainers have discussed this further. Even as acquainted with this project as we are, we have found the complexity and nuance of many concepts has made documentation a challenging task, even in our native language. We are unanimously concerned that a “word for word” translation by anyone lacking familiarity with the concepts is likely to lose nuance and accuracy which might otherwise be preserved by a translator who _is_ so acquainted. With no maintainer being proficient in Spanish, we also lack the capacity to assert the accuracy of the translations ourselves.

Equally concerning to us is the model by which you have expressed you would be paid for your contributions. If you’re paid for translations of only a certain size, it’s not clear to us that there’s an incentive for you to make small (but important), incremental updates to the Spanish docs on an on-going basis to keep them in parity with the English docs. Without someone dedicated to keeping the translations up to date, we fear they will _very quickly_ become so stale as to be virtually useless.

We appreciate your interest in our project, but since we just don’t know how to guarantees accuracy and ongoing maintenance of what you’re offering us at this time, we cannot accept such PRs.
