### ISSUE TITLE
Error creating Pod

### ISSUE THREAD

**Issue by andrehe001** [Azure/open-service-broker-azure#432]
After following the steps in the doc, successfully creating a cluster and adding all necessary items, I get following error when installing the wordpress sample :
PersistentVolumeClaim is not bound: "osba-wordpress-wordpress" (repeated 3 times) 
Unable to mount volumes for pod "osba-wordpress-wordpress-9994f655-ntzbr_osba-wordpress(0b4985c6-5501-11e8-b59c-0a58ac1f04f2)": timeout expired waiting for volumes to attach/mount for pod "osba-wordpress"/"osba-wordpress-wordpress-9994f655-ntzbr". list of unattached/unmounted volumes=[wordpress-data] 
Error: secrets "osba-wordpress-wordpress-mysql-secret" not found 

I've added a picture with all the messages. Anyone run into this and had a solution?

![pod-error](https://user-images.githubusercontent.com/13762183/39919352-a172ed4c-5513-11e8-8370-a6eea14029aa.png)

**Comment by andrehe001** [comment]
The error message writes, that the persistent volume claim is not bound but it is as seen in the picture on the bottom. Anyone know, why it cannot mount the volume even as the persistent volume claim is ready?

**Comment by jeremyrickard** [comment]
@andrehe001 did you ever get past this? It looks like the PVC took a bit and eventually was bound (09:56 UTC) in that and then it went on to start the next part of the container startup, which would have referenced the secret created by the binding. 

In the case of the secret created by the binding, it won't actually get created until the binding is successful. The binding won't be successful until after the instance is provisioned. Sometimes you end up in a prolonged CrashBackoffLoop because the instance takes a bit of time to deploy and everything just sort of cascades from there with the exponential backoff. 

Feel free to ping me on the kubernetes slack if you are still having issues here.

**Comment by zhongyi-zhang** [comment]
Feel free to reopen if you want to follow up.
