### ISSUE TITLE
lost secret after upgrading Kubernetes

### ISSUE THREAD

**Issue by dewnull** [Azure/open-service-broker-azure#534]
I upgrade my Azure Cluster from Kubernetes version 1.10.3 to 1.10.5 and I lost my binding and secret for my provisioned PostgreSQL database. Is this related to not setting `apiserver.storage.etcd.persistence.enabled` to `true`?

**Comment by jeremyrickard** [comment]
That is the most likely outcome. Unless you use that flag, the etcd container is not backed by persistent volume. In that case, when the you do that upgrade, the pods are restarting and you’ll lose the state etcd had at that point (and Service Catalog currently requires that etcd for storage of the resources you’ve created)

**Comment by krancour** [comment]
imo, Service Catalog really should default to a persistent etcd.

@dewnull not sure if this is production or not, but please do note that if running in productions, you should be running an HA etcd cluster within your k8s cluster (via the etcd operator, probably) instead of using the embedded etcd that comes with Service Catalog.

This is definitely not a broker issue, so I'm going to close this.
