### ISSUE TITLE
Question: How can you set defaults for the models in use?

### ISSUE THREAD

**Issue by Stijnc** [Azure/open-service-broker-azure#538]
#How to set service broker defaults
From the documentation I understand that you can set [certain defaults like resource group etc.](https://github.com/Azure/open-service-broker-azure/blob/master/docs/modules/mysql.md#behaviors)
But I can't seem to find any other reference in the documentation or Helm chart.

How, as an Operations Guy can I set certain defaults?

In addition, what is the behavior when azure policies are applied to limit deployments to certain regions, sku's and enforce naming conventions?

**Comment by krancour** [comment]
> From the documentation I understand that you can set certain defaults like resource group etc.

At one time, long prior to the GA release, you could specify default location and resource group when deploying the broker. If those were set, those two parameters became optional on all service/plan provisioning parameters. If they were still included in the provisioning parameters, they would override the defaults.

For reasons that are to complex to explain succinctly, we eventually concluded that it was best to not treat _any_ parameters as special. From that point on (maybe three months ago) the mechanism for specifying a global default location and resource group was removed and those corresponding provisioning parameters are now _always_ required for any service/plan where those are relevant-- which is most of them.

I thought all documentation was updated accordingly after that change, but if you can point me to any docs that may be misleading you, I'll be happy to correct them. (I can't spot where in the doc you linked to where there may be stale information.)

> How, as an Operations Guy can I set certain defaults?

Since you referenced the Helm chart, I'll assume your platform of choice is Kubernetes. In that case, we expect that this need will be, eventually, be fulfilled through a feature in Kubernetes Service Catalog that allows an operator to define reusable templates for service/plan provisioning parameters with params pre-filled to their liking. @jeremyrickard or @carolynvs can probably point you to specifics, but it is still a WIP as I understand it.

> In addition, what is the behavior when azure policies are applied to limit deployments to certain regions, sku's and enforce naming conventions?

The broker doesn't currently have a way of dealing with this. It also doesn't have a way of dealing with the fact that not all services are available in all regions. Dynamically validating a provisioning request against these kind of constraints isn't something I expect we can tackle in the near future. Obviously it would be a maintenance burden to keep this information up to date manually, and to the best of my knowledge, an API for us to query the availability of services in different regions doesn't exist (yet).

**Comment by Stijnc** [comment]
Hi @krancour, 

thank for the explaination.
I found the options on the different model provision sections mention this. 
For example:  the [eventhubs provision section](https://github.com/Azure/open-service-broker-azure/blob/master/docs/modules/eventhubs.md) repeatedly states:

> If an administrator has configured the broker itself with a default <propertyname> and none is specified, that default will be applied, otherwise ...

I'm just starting with kubernetes, but could this be a usecase for [admission controls](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/)?

**Comment by krancour** [comment]
@Stijnc thanks for the pointer there to some docs that definitely need an update. I'll get that squared away.

> I'm just starting with kubernetes, but could this be a usecase for admission controls?

My understanding is that admission controls are for validating and authorizing request-- not for modifying them. I could very well be wrong about that. Still, I expect the "template" feature that Service Catalog is working on will be the way to go.

**Comment by jeremyrickard** [comment]
I agree with @krancour that the default stuff that svc cat is working on is the end goal you want and we'd welcome participation (even in terms of just validating experience or use cases!), but you could probably implement this with an [Admission Webhook](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook-beta-in-1-9) for now. 


There are two flavors, depending on what you want to do:

>Admission controllers may be “validating”, “mutating”, or both. Mutating controllers may modify the objects they admit; validating controllers may not.

So for the first one...

> Mutating controllers may modify the objects they admit

So here you _could_ override the `ServiceInstance` request that was coming in. There was some talk within the service catalog group about using this to hack in Cloud Foundry's VCAP_SERVICES behavior for bound services, you could probably implement something to achieve what you want above. You could do something similar to change a region or plan reference (harder..restricting that sort of thing would be better with namespaced resources and catalog restrictions)

> validating controllers may not.

Here you could provide a validating web hook that rejected requests for `ServiceInstance`s  that didn't conform to your organization's rules.

**Comment by krancour** [comment]
This seems like it was answered, so closing.
