### ISSUE TITLE
Is there any special concern keeping the cosmos module as `Experimental`?

### ISSUE THREAD

**Issue by norshtein** [Azure/open-service-broker-azure#551]
Hi, we are using the cosmos module recently, but seems every plan under this module has  `StabilityExperimental`. From our point of view, this module works pretty well. Is there any special concern keeping the cosmos module as `Experimental`?

**Comment by jeremyrickard** [comment]
Probably not. I think we can probably move it up to `preview`?

In general, we had left everything in experimental because we weren't sure if they'd change or not. I think we've made most of the changes that might be considered breaking changes (like plans/etc). Adding parameters at this point can be additive. 

@norshtein do you want to open a PR for that?

**Comment by krancour** [comment]
@jeremyrickard, before we graduate modules to stable or even preview, I think we should have arrived at a general feeling that the services and plans in question provide an experience we're happy with and think we can live with long term. You know more about this module than I do. Are we there?

**Comment by jeremyrickard** [comment]
@krancour yeah, sorry that was implied by my "i think we can move it up to preview".  I *think* we've mostly gotten the experience up to par. It might be useful to get that multi-read region stuff in before preview, but I think we're providing mostly what is needed.
